config/routes.rb
Rails.application.routes.draw do

  root "home#index"
  get "/about" => "home#about"

  resources :users, only: [:new, :create] do
    get :edit, on: :collection
    patch :update, on: :collection
    get :edit_password, on: :collection
    patch :update_password, on: :collection
  end

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

  resources :guest_sessions, only: :create

  resources :posts do
    resources :comments, only: [:create, :destroy, :edit, :update]
    resources :favorites, only: [:create, :destroy]
  end

  resources :favorites, only: :index

  match "*path", to: redirect("/"), via: :get

end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
  belongs_to :post

  validates :user_id, uniqueness: {scope: :post_id}
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  before_action :authenticate_user!

  def create
    favorite = Favorite.new
    favorite.user = current_user
    favorite.post = post
    respond_to do |format|
      if favorite.save
        format.html { redirect_to post, notice: "Favorite saved!" }
        format.js   { render }
      else
        format.html { redirect_to post, alert: "You'va already make this into your favorite!" }
        format.js   { render js: "alert('Can\'t favorite, please refresh the page!');" }
      end
    end
  end

  def index
    @posts = current_user.favorite_posts.order(:title).page(params[:page]).per(9)
  end

  def destroy
    post
    favorite = Favorite.find params[:id]
    favorite.destroy
    respond_to do |format|
      format.html { redirect_to post_path(favorite.post_id), notice: "Favorite deleted!" }
      format.js { render }
    end
  end

  private

  def post
    @post ||= Post.find params[:post_id]
  end

  def favorite
    @favorite ||= Favorite.find params[:id]
  end

end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/_favorite.html.erb
<% if user_signed_in? %>
  <% bool = true %>
<% else %>
  <% bool = false %>
<% end %>

<% if user_favorite %>
  <%= link_to post_favorite_path(@post, user_favorite), method: :delete, remote: bool, class: "fav-icon" do %>
    <span class="glyphicon glyphicon-heart text-danger"><span class="favorite-label">Favorite</span></span>
  <% end %>
<% else %>
  <%= link_to post_favorites_path(@post), method: :post, remote: bool, class: "fav-icon" do %>
    <span class="glyphicon glyphicon-heart-empty text-danger"><span class="favorite-label">Favorite</span></span>
  <% end %>
<% end %>

<span>(<%= @post.favorites.count %>)</span>

app/views/favorites/create.js.erb
$("#post-favorite").html("<%= j render 'favorite' %>");

app/views/favorites/destroy.js.erb
$("#post-favorite").html("<%= j render 'favorite' %>");

app/views/favorites/index.html.erb
<h1>Favorite Posts</h1>

<% if @posts.present? %>
  <%= render "/posts/post" %>
<% else %>
  <h3>You have no favorite posts.</h3>
<% end %>

<div class="col-xs-12 posts-pagination">
  <%= paginate @posts %>
  <%= page_entries_info @posts %>
</div>