config/routes.rb
Rails.application.routes.draw do

  root "home#index"
  get "/about" => "home#about"

  resources :users, only: [:new, :create] do
    get :edit, on: :collection
    patch :update, on: :collection
    get :edit_password, on: :collection
    patch :update_password, on: :collection
  end

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

  resources :guest_sessions, only: :create

  resources :posts do
    resources :comments, only: [:create, :destroy, :edit, :update]
    resources :favorites, only: [:create, :destroy]
  end

  resources :favorites, only: :index

  match "*path", to: redirect("/"), via: :get

end

app/models/comment.rb
class Comment < ActiveRecord::Base

  belongs_to :user
  belongs_to :post

  validates :body, presence: true, uniqueness: {scope: :post_id}

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_post
  before_action :find_and_authorize_comment, only: [:destroy, :edit, :update]

  def create
    @comment          = Comment.new comment_params
    @comment.post     = @post
    @comment.user     = current_user
    respond_to do |format|
      if @comment.save
        format.html { redirect_to post_path(@post), notice: "Thanks for your comment." }
        format.js { render :create_success }
      else
        flash.now[:alert] = "Comment not saved!"
        format.html { render "/posts/show" }
        format.js { render :create_failure }
      end
    end
  end

  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to post_path(@post), notice: "Comment deleted!" }
      format.js { render }
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @comment.update comment_params
        format.js { render :update_success }
      else
        format.js { render :update_failure }
      end
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:body)  
  end

  def find_post
    @post = Post.find params[:post_id]
  end

  def find_and_authorize_comment
    @comment = @post.comments.find params[:id]
    redirect_to root_path unless can? :crud, @comment
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div id="<%= dom_id(comment) %>" class="well well-sm" style="<%= style if defined?(style) %>">
  <div class="comment-user-name"><strong><%= comment.user.full_name.titleize %></strong></div>
  <div class="comment-body"><%= comment.body %></div>

  <div class="edit-delete-btns">
    <% if can? :edit, comment %>
      <%= link_to "Edit", edit_post_comment_path(@post, comment),
                        remote: true,
                        data: {toggle: "modal", target: "#edit-comment"},
                        class: "btn btn-default btn-xs"
                        %>
    <% end %>
    <% if can? :destroy, comment %>
      <%= link_to "Delete", post_comment_path(@post, comment),
                            method: :delete,
                            remote: true,
                            data: {confirm: "Are you sure?"},
                            class: "btn btn-danger btn-xs" %>
    <% end %>
  </div>
</div>

app/views/comments/_form.html.erb
<% if user_signed_in? %>
  <% bool = true %>
<% else %>
  <% bool = false %>
<% end %>

<%= form_for [@post, comment], remote: bool do |f| %>
  <div class="form-group">
    <%= f.text_area :body, class: "form-control" %>
  </div>
  <%= f.submit data: {disable_with: "submitting..."}, class: "btn btn-primary btn-sm" %>
<% end %>
<br>
<%= comment.errors.full_messages.join(", ") %>

app/views/comments/_modal_form.html.erb
<%= form_for [@post, @comment], remote: true do |f|  %>
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Edit Comment</h4>
      </div>
      <div class="modal-body form-group">
        <%= f.text_area :body, class: "form-control" %>
        <%= @comment.errors.full_messages.join(", ") %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <%= f.submit data: {disable_with: "submitting..."}, class: "btn btn-primary" %>
      </div>
    </div>
  </div>
<% end %>

app/views/comments/create_failure.js.erb
$("#comment-form").html("<%= j render '/comments/form', comment: @comment %>");

app/views/comments/create_success.js.erb
$("#comments").prepend("<%= j render '/comments/comment', comment: @comment, style: 'display: none' %>");
$("#comment-form").html("<%= j render '/comments/form', comment: Comment.new %>");
$("#<%= dom_id(@comment) %>").slideDown(1000);

app/views/comments/destroy.js.erb
$("#<%= dom_id(@comment) %>").slideUp(1000, function(){
  $(this).remove();
});

app/views/comments/edit.js.erb
$("#edit-comment").html("<%= j render 'modal_form' %>");

app/views/comments/update_failure.js.erb
$("#edit-comment").html("<%= j render 'modal_form', comment: @comment %>");

app/views/comments/update_success.js.erb
$("#edit-comment").modal('hide')

$("#<%= dom_id(@comment) %>").html("<%= j render '/comments/comment', comment: @comment%>").css("display",  "none" );
$("#<%= dom_id(@comment) %>").fadeIn(1000);