config/routes.rb
Rails.application.routes.draw do

  root "home#index"
  get "/about" => "home#about"

  resources :users, only: [:new, :create] do
    get :edit, on: :collection
    patch :update, on: :collection
    get :edit_password, on: :collection
    patch :update_password, on: :collection
  end

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

  resources :guest_sessions, only: :create

  resources :posts do
    resources :comments, only: [:create, :destroy, :edit, :update]
    resources :favorites, only: [:create, :destroy]
  end

  resources :favorites, only: :index

  match "*path", to: redirect("/"), via: :get

end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password

  has_many :posts,    dependent: :nullify
  has_many :comments, dependent: :nullify

  has_many :favorites, dependent: :destroy
  has_many :favorite_posts, through: :favorites, source: :post


  validates :first_name, presence: true
  validates :last_name, presence: true

  VALID_EMAIL_REGEX = /\A([\w+\-]\.?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :email, uniqueness: true, presence: true, format: VALID_EMAIL_REGEX

  def full_name
    "#{first_name} #{last_name}"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :redirect_if_signed_in, only: [:new, :create]
  before_action :authenticate_user!, except: [:new, :create]

  def new
    @user = User.new
  end

  def create
    user_params = params.require(:user).permit(:first_name, :last_name, :email,
                                               :password, :password_confirmation)
    @user = User.new user_params
    if @user.save
      sign_in(@user)
      redirect_to root_path, notice: "Account created!"
    else
      flash.now[:alert] = "Account not created! Missing fields!"
      render :new
    end
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    user_params = params.require(:user).permit(:first_name, :last_name, :email)
    if @user.update user_params
      redirect_to root_path, notice: "User info updated!"
    else
      redirect_to edit_users_path, alert: "User info not updated!"
    end
  end

  def edit_password
    @user = current_user
  end

  def update_password
    @user = current_user
    if @user && @user.authenticate(params.require(:user).permit(:current_password)[:current_password])

      if params.require(:user).permit(:password)[:password] == params.require(:user).permit(:current_password)[:current_password]
        redirect_to edit_password_users_path, alert: "New password has to be different from the current password!"
      elsif @user.update params.require(:user).permit(:password, :password_confirmation)
        redirect_to root_path, notice: "Password updated!"
      else
        redirect_to edit_password_users_path, alert: "Password not updated!"
      end

    else
      redirect_to edit_password_users_path, alert: "Wrong password!"
    end
  end

  private

  def redirect_if_signed_in
    if user_signed_in?
      redirect_to session[:my_previous_url], notice: "Signed in as #{current_user.first_name}!"
      session[:my_previous_url] = ""
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<h1>Edit User Info</h1>

<% if @user.errors.any? %>
  <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @user, url: users_path do |f| %>
  <div class="form-group">
    <%= f.label :first_name %>
    <%= f.text_field :first_name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :last_name %>
    <%= f.text_field :last_name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :email %>
    <%= f.email_field :email, class: "form-control" %>
  </div>
  <div>
    <%= f.submit "Update Info", class: "btn btn-primary" %>
  </div>
<% end %>

<br>
<%= link_to "Change Password", edit_password_users_path, class: "btn btn-warning btn-sm" %>

app/views/users/edit_password.html.erb
<h1>Change Password</h1>

<% if @user.errors.any? %>
  <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @user, url: update_password_users_path do |f| %>
  <div class="form-group">
    <%= f.label :current_password %>
    <%= f.password_field :current_password, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :new_password %>
    <%= f.password_field :password, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :new_password_confirmation %>
    <%= f.password_field :password_confirmation, class: "form-control" %>
  </div>
  <div>
    <%= f.submit "Change Password", class:"btn btn-primary" %>
  </div>
<% end %>

app/views/users/new.html.erb
<h1>New Account</h1>

<% if @user.errors.any? %>
  <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @user do |f| %>
  <div class="form-group">
    <%= f.label :first_name %>
    <%= f.text_field :first_name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :last_name %>
    <%= f.text_field :last_name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :email %>
    <%= f.email_field :email, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class: "form-control" %>
  </div>
  <div>
    <%= f.submit "Create an Account", class: "btn btn-primary" %>
  </div>
<% end %>