config/routes.rb
Rails.application.routes.draw do

  root "home#index"
  get "/about" => "home#about"

  resources :users, only: [:new, :create] do
    get :edit, on: :collection
    patch :update, on: :collection
    get :edit_password, on: :collection
    patch :update_password, on: :collection
  end

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

  resources :guest_sessions, only: :create

  resources :posts do
    resources :comments, only: [:create, :destroy, :edit, :update]
    resources :favorites, only: [:create, :destroy]
  end

  resources :favorites, only: :index

  match "*path", to: redirect("/"), via: :get

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    user ||= User.new

    can :manage, :all if user.admin?

    alias_action :create, :read, :update, :destroy, :to => :crud

    can :crud, Comment do |c|
      (c.post.user == user || c.user == user) && user.persisted?
    end

    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/category.rb
class Category < ActiveRecord::Base

  has_many :posts, dependent: :nullify

  validates :title, presence: true, uniqueness: true

end

app/models/comment.rb
class Comment < ActiveRecord::Base

  belongs_to :user
  belongs_to :post

  validates :body, presence: true, uniqueness: {scope: :post_id}

end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
  belongs_to :post

  validates :user_id, uniqueness: {scope: :post_id}
end

app/models/post.rb
class Post < ActiveRecord::Base

  belongs_to :user
  belongs_to :category
  has_many :comments, dependent: :destroy

  has_many :sections, dependent: :destroy
  accepts_nested_attributes_for :sections,
                                reject_if:     :all_blank,
                                allow_destroy: true

  has_many :favorites, dependent: :destroy
  has_many :favoriting_users, through: :favorite, source: :user

  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings


  validates :title, presence: true, uniqueness: true, length: { minimum: 7 }
  validates :body, presence: true
  validates :category, presence: true
  validates :image, presence: true

  mount_uploader :image, ImageUploader

  def self.search(search)
    eager_load(:sections).where( "title ILIKE :term OR body ILIKE :term OR sections.description ILIKE :term", term: "%#{search}%" )
  end

  def body_snippet
    body.length > 100 ? body[0...100] + "..." : body
  end

  def favorite_for(user)
    favorites.find_by_user_id user if user
  end

end

app/models/section.rb
class Section < ActiveRecord::Base
  belongs_to :post

  validates :image, presence: true
  validates :description, presence: true

  mount_uploader :image, ImageUploader
end

app/models/tag.rb
class Tag < ActiveRecord::Base

  has_many :taggings, dependent: :destroy
  has_many :posts, through: :taggings

  validates :name, presence: true, uniqueness: true

end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :post
  belongs_to :tag

  validates :post_id, uniqueness: { scope: :tag_id}
end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password

  has_many :posts,    dependent: :nullify
  has_many :comments, dependent: :nullify

  has_many :favorites, dependent: :destroy
  has_many :favorite_posts, through: :favorites, source: :post


  validates :first_name, presence: true
  validates :last_name, presence: true

  VALID_EMAIL_REGEX = /\A([\w+\-]\.?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :email, uniqueness: true, presence: true, format: VALID_EMAIL_REGEX

  def full_name
    "#{first_name} #{last_name}"
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @posts = Post.order(:id).last(3)
  end

  def about
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :find_post, only: [:show, :edit, :update, :destroy]
  before_action :authorize_post, only: [:new, :create, :edit, :update, :destroy]

  def new
    @post = Post.new
  end

  def create
    @post = Post.new post_params
    @post.user  = current_user
    if @post.save
      redirect_to post_path(@post), notice: "New blog post created!"
    else
      flash.now[:alert] = "Blog post not created!"
      render :new
    end
  end

  def show
    @comment = Comment.new
  end

  def index
    if params[:search]
      @posts = Post.search(params[:search]).order(id: :desc).page(params[:page]).per(9)
    else
      @posts = Post.all.order(id: :desc).page(params[:page]).per(9)
    end

  end

  def edit
  end

  def update
    if @post.update post_params
      redirect_to post_path(@post), notice: "Blog post updated!"
    else
      flash.now[:alert] = "Blog post not updated!"
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path, notice: "Blog post deleted!"
  end

  private

  def authorize_post
    redirect_to root_path unless can? :crud, @post
  end

  def find_post
    @post = Post.find params[:id]
  end

  def post_params
    params.require(:post).permit(:title, :image, :body, :category_id, tag_ids: [], sections_attributes: [:image, :description, :id, :_destroy])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :redirect_if_signed_in, only: [:new, :create]
  before_action :authenticate_user!, except: [:new, :create]

  def new
    @user = User.new
  end

  def create
    user_params = params.require(:user).permit(:first_name, :last_name, :email,
                                               :password, :password_confirmation)
    @user = User.new user_params
    if @user.save
      sign_in(@user)
      redirect_to root_path, notice: "Account created!"
    else
      flash.now[:alert] = "Account not created! Missing fields!"
      render :new
    end
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    user_params = params.require(:user).permit(:first_name, :last_name, :email)
    if @user.update user_params
      redirect_to root_path, notice: "User info updated!"
    else
      redirect_to edit_users_path, alert: "User info not updated!"
    end
  end

  def edit_password
    @user = current_user
  end

  def update_password
    @user = current_user
    if @user && @user.authenticate(params.require(:user).permit(:current_password)[:current_password])

      if params.require(:user).permit(:password)[:password] == params.require(:user).permit(:current_password)[:current_password]
        redirect_to edit_password_users_path, alert: "New password has to be different from the current password!"
      elsif @user.update params.require(:user).permit(:password, :password_confirmation)
        redirect_to root_path, notice: "Password updated!"
      else
        redirect_to edit_password_users_path, alert: "Password not updated!"
      end

    else
      redirect_to edit_password_users_path, alert: "Wrong password!"
    end
  end

  private

  def redirect_if_signed_in
    if user_signed_in?
      redirect_to session[:my_previous_url], notice: "Signed in as #{current_user.first_name}!"
      session[:my_previous_url] = ""
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def user_favorite
    @user_favorite ||= @post.favorite_for(current_user)
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_analytics.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-80734792-1', 'auto');
  ga('send', 'pageview');

</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Yii Van's Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>

  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to root_path, class: "navbar-brand" do %>
          <strong>Yii Van's Blog</strong>
        <% end %>
      </div>

      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li><%= link_to "About", about_path %></li>

          <li><%= link_to "Blog", posts_path %></li>
          <li>
            <% if can? :create, @post %>
              <%= link_to "Create Blog Post", new_post_path %>
            <% end %>
          </li>
        </ul>
        <%= form_tag posts_path, method: :get, id: "search-form", class: "navbar-form navbar-left" do %>
          <div class="form-group">
            <%= text_field_tag :search, params[:search], placeholder: "Search Posts...", class: "form-control" %>
          </div>
          <%= submit_tag "Search", class: "btn btn-default" %>
        <% end %>
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li><%= link_to "My Favorite Posts", favorites_path %></li>
            <li><%= link_to current_user.first_name, edit_users_path%></li>
            <li><%= link_to "Sign out", sessions_path, method: :delete %></li>
          <% else %>
            <li><%= link_to "Sign In", new_session_path %></li>
            <li><%= link_to "Register", new_user_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>

  <div class="container">
    <% if notice %>
      <div class="alert alert-success alert-dismissible" >
        <button type="button" class="close" data-dismiss="alert"><span>&times;</span></button>
        <%= notice %>
      </div>
    <% elsif alert %>
      <div class="alert alert-danger alert-dismissible" >
        <button type="button" class="close" data-dismiss="alert"><span>&times;</span></button>
        <%= alert %>
      </div>
    <% else %>
      <div></div>
    <% end %>

    <%= yield %>
  </div>

  <%= render "/layouts/analytics" if Rails.env.production? %>

</body>
</html>